#cloud-config
users:
  - name: scott
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH82S0+HrmiQM/ZmXi/Xd9l8IfWvnUPt1GOxcgyj56l/

packages:
  - fail2ban
  - ufw
  - git
  - uv
  - python3
package_update: true
package_upgrade: true

write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      MaxAuthTries 2
      AllowUsers scott

runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow 22
  - ufw allow 80
  - ufw allow 443
  - ufw enable
  - reboot